id = "gdscript"
name = "GDScript"
version = "0.3.3"
schema_version = 1
authors = [
    "Mark Brand <mark@grndctrl.com>",
    "Richard Taylor <moomerman@gmail.com>",
    "Radu Gafita <radugaf@gmail.com>"
]
description = "GDScript language support for Zed"
repository = "https://github.com/grndctrl/zed-gdscript"

[language_servers.gdscript]
name = "GDScript Language Server"
language = "GDScript"

[grammars.gdscript]
repository = "https://github.com/PrestonKnopp/tree-sitter-gdscript"
commit = "1f1e782fe2600f50ae57b53876505b8282388d77"

[grammars.godot_resource]
repository = "https://github.com/PrestonKnopp/tree-sitter-godot-resource"
commit = "2ffb90de47417018651fc3b970e5f6b67214dc9d"
