name = "GDScript"
grammar = "gdscript"
path_suffixes = ["gd"]
line_comments = ["# ", "## "]
brackets = [
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "{", end = "}", close = true, newline = true },
]
auto_indent_using_last_non_empty_line = false
increase_indent_pattern = ":\\s*$"
